#!/usr/bin/env node
/*
 * Download the exhibition's typefaces from Google Fonts and serve them locally.
 *
 * Why: a gallery kiosk often runs on an isolated network with no route to the
 * internet. A render-blocking <link> to fonts.googleapis.com then stalls the
 * first paint until it times out and finally falls back to a system serif —
 * on the one screen whose whole character is its typography. Self-hosting also
 * removes a third-party request from a public exhibit.
 *
 * Writes public/fonts/*.woff2 and public/fonts/fonts.css.
 *
 *   node tools/fetch-fonts.mjs
 */
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';

// Matches the families and weights the stylesheet actually asks for.
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Cinzel:wght@400;600;700' +
  '&family=Cinzel+Decorative:wght@400;700' +
  '&family=Spectral:ital,wght@0,300;0,400;0,500;1,300;1,400' +
  '&display=swap';

// A modern desktop UA makes Google serve woff2 rather than older formats.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0 Safari/537.36';

// The saints include names such as Adomnán and Máel — keep latin-ext.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const root = path.resolve(import.meta.dirname, '..');
const outDir = path.join(root, 'public', 'fonts');
mkdirSync(outDir, { recursive: true });

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!res.ok) {
  console.error(`Could not reach Google Fonts (HTTP ${res.status}). Are you online?`);
  process.exit(1);
}
let css = await res.text();

// Google emits a `/* latin */` style comment before each @font-face block.
const blocks = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1);
const kept = [];
let downloaded = 0;
let bytes = 0;

for (let i = 0; i < blocks.length; i += 2) {
  const subset = blocks[i];
  let block = blocks[i + 1];
  if (!KEEP_SUBSETS.has(subset) || !block.includes('@font-face')) continue;

  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] || '400';
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] || 'normal';
  if (!url || !family) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;
  const dest = path.join(outDir, file);

  if (!existsSync(dest)) {
    const font = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!font.ok) { console.warn(`  ! failed: ${file}`); continue; }
    const buf = Buffer.from(await font.arrayBuffer());
    writeFileSync(dest, buf);
    downloaded += 1;
    bytes += buf.length;
  }
  kept.push(block.replace(url, `/fonts/${file}`).trim());
}

if (!kept.length) {
  console.error('No @font-face blocks were parsed — Google may have changed its CSS format.');
  process.exit(1);
}

writeFileSync(
  path.join(outDir, 'fonts.css'),
  `/* Generated by tools/fetch-fonts.mjs — do not hand-edit.\n` +
  `   Self-hosted so the kiosk renders correctly with no internet access. */\n\n` +
  kept.join('\n\n') + '\n'
);

console.log(
  `\n  Fonts → public/fonts\n` +
  `  ${downloaded} downloaded, ${kept.length} @font-face rules written ` +
  `(${(bytes / 1024).toFixed(0)} KB)\n`
);
