/* Build CREDITS.md from data/credits.json (image attributions). */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const credits = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'credits.json'), 'utf8'));
const saints = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'saints.final.json'), 'utf8'));

const rows = saints
  .filter((s) => s.image && credits[s.id])
  .map((s) => {
    const c = credits[s.id];
    const artist = (c.artist || '—').replace(/\|/g, '/');
    const license = c.license || '—';
    const link = c.descriptionUrl || c.source || '';
    return `| ${s.name} | ${artist} | ${license} | ${link ? `[file](${link})` : '—'} |`;
  });

const noImage = saints.filter((s) => !s.image).map((s) => s.name);
const monoNote = noImage.length
  ? `${noImage.length} saint${noImage.length === 1 ? '' : 's'} (${noImage.join(', ')}) had no suitable image and are shown with a typographic monogram instead.`
  : 'Every saint has an image.';

const md = `# Image credits

All saint portraits are sourced from **Wikimedia Commons / Wikipedia** and are
predominantly public-domain artworks (paintings, icons, stained glass, statues)
or freely-licensed photographs. Each image was retrieved via the MediaWiki API
by \`tools/fetch-images.mjs\`. Licences and authors below are as reported by
Commons at the time of download — consult the linked file page for the
authoritative, current licensing terms before any reuse beyond this exhibition.

${monoNote}

| Saint | Author / source | Licence | File |
| --- | --- | --- | --- |
${rows.join('\n')}

_Generated by \`tools/gen-credits.mjs\` — ${rows.length} attributed images._
`;

fs.writeFileSync(path.join(ROOT, 'CREDITS.md'), md);
console.log(`CREDITS.md written with ${rows.length} entries`);
