/*
 * Map + pin generator.
 *
 * Reads real GISCO country geometry (WGS84), fits ONE projection over the
 * UK + Ireland, and bakes:
 *   - public/map.js     accurate SVG path strings + viewBox
 *   - public/saints.js  the saint dataset with each pin projected to x/y
 *                        (only when data/saints.final.json exists)
 *
 * Because pins use the very same projection as the coastline, they land
 * exactly where they belong.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { geoMercator, geoPath, geoBounds } from 'd3-geo';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

// Prefer the trimmed copy committed to the repo; fall back to a fresh GISCO download.
const REPO_GEO = path.resolve(__dirname, '..', 'data', 'uk-ie.geo.json');
const GEO_SRC = process.env.GEO_SRC || (fs.existsSync(REPO_GEO) ? REPO_GEO : '/tmp/gisco_3m.geojson');
const W = 720;
const H = 960;
const PAD = 26;

// ---- Load + extract UK and Ireland -----------------------------------------
const fc = JSON.parse(fs.readFileSync(GEO_SRC, 'utf8'));
const idOf = (f) => f.properties.CNTR_ID || f.properties.id || f.properties.ISO2;
const uk = fc.features.find((f) => idOf(f) === 'UK');
const ie = fc.features.find((f) => idOf(f) === 'IE');
if (!uk || !ie) throw new Error('Could not find UK and IE in ' + GEO_SRC);

// Drop the very tiniest islets so the silhouette stays clean (keeps Man,
// Wight, Anglesey, Skye, the Hebrides, Orkney, Shetland, Arran, etc.).
const MIN_AREA = 0.0009; // square degrees
function ringArea(ring) {
  let a = 0;
  for (let i = 0, n = ring.length, j = n - 1; i < n; j = i++) {
    a += (ring[j][0] * ring[i][1]) - (ring[i][0] * ring[j][1]);
  }
  return Math.abs(a) / 2;
}
function pruneTinyIslands(feature) {
  const g = feature.geometry;
  if (g.type !== 'MultiPolygon') return feature;
  const kept = g.coordinates.filter((poly) => ringArea(poly[0]) >= MIN_AREA);
  return { ...feature, geometry: { type: 'MultiPolygon', coordinates: kept } };
}
const ukC = pruneTinyIslands(uk);
const ieC = pruneTinyIslands(ie);

// ---- One shared projection over both landmasses ----------------------------
const both = { type: 'FeatureCollection', features: [ukC, ieC] };
const projection = geoMercator().fitExtent([[PAD, PAD], [W - PAD, H - PAD]], both);
const toPath = geoPath(projection);

// Trim path-string number precision to 1 dp — invisible at this scale, far smaller file.
const trim = (d) => d.replace(/-?\d+\.\d+/g, (m) => Number(m).toFixed(1));
const ukPath = trim(toPath(ukC));
const iePath = trim(toPath(ieC));

// ---- Emit public/map.js ----------------------------------------------------
const mapJs = `/* Auto-generated by tools/genmap.mjs — real GISCO geometry, do not hand-edit. */
window.UK_MAP = {
  viewBox: '0 0 ${W} ${H}',
  width: ${W},
  height: ${H},
  uk: ${JSON.stringify(ukPath)},
  ireland: ${JSON.stringify(iePath)}
};
`;
fs.writeFileSync(path.join(ROOT, 'public', 'map.js'), mapJs);
console.log(`map.js written — uk path ${ukPath.length} chars, ireland ${iePath.length} chars`);

// ---- Calibration check -----------------------------------------------------
const calib = {
  'London': [-0.1278, 51.5074],
  'Edinburgh': [-3.1883, 55.9533],
  'Cardiff': [-3.1791, 51.4816],
  'Belfast': [-5.9301, 54.5973],
  "Land's End": [-5.7132, 50.0657],
  "John o' Groats": [-3.0689, 58.6373],
  'Canterbury': [1.0789, 51.2802],
  'Iona': [-6.41, 56.33],
};
console.log('\nCalibration (x,y in 0..%d / 0..%d):', W, H);
for (const [name, lnglat] of Object.entries(calib)) {
  const [x, y] = projection(lnglat);
  console.log(`  ${name.padEnd(16)} -> ${x.toFixed(1)}, ${y.toFixed(1)}`);
}

// ---- Emit public/saints.js (only when the final list is present) -----------
const finalPath = path.join(ROOT, 'data', 'saints.final.json');
if (fs.existsSync(finalPath)) {
  const saints = JSON.parse(fs.readFileSync(finalPath, 'utf8'));
  let placed = 0;
  const withXY = saints.map((s) => {
    const [x, y] = projection([s.lng, s.lat]);
    placed++;
    return { ...s, map: { x: Number(x.toFixed(1)), y: Number(y.toFixed(1)) } };
  });
  const banner = `/* Auto-generated by tools/genmap.mjs from data/saints.final.json. */\n`;
  fs.writeFileSync(
    path.join(ROOT, 'public', 'saints.js'),
    banner + 'window.SAINTS = ' + JSON.stringify(withXY, null, 2) + ';\n'
  );
  console.log(`\nsaints.js written — ${placed} saints projected onto the map`);
} else {
  console.log('\n(no data/saints.final.json yet — skipped saints.js)');
}
